version: '3'
services:
  eureka:
    image: odysseusinc/service-discovery-svr:0.0.1-SNAPSHOT
    expose:
      - "8761"
    env_file:
      - ./common.env
      - ./service-discovery-svr/common.env
    networks:
      - services
  proxy:
    image: odysseusinc/proxy-svr:0.0.1-SNAPSHOT
    ports:
      - "5555"
    env_file:
      - ./common.env
    depends_on:
      - eureka
    networks:
      - services
  execution-engine:
    image: odysseusinc/execution-engine-cloud:1.4.0-SNAPSHOT
    env_file:
      - ./common.env
      - ./execution-engine/dev.env
    depends_on:
      - eureka
      - proxy
    networks:
      - services
    extra_hosts:
      - "postgres:${POSTGRES_IP}"
  webapi:
    image: odysseusinc/webapicloud:2.7.2-SNAPSHOT
    env_file:
      - ./common.env
      - ./webapi/dev.env
    depends_on:
      - eureka
      - proxy
    extra_hosts:
      - "postgres:${POSTGRES_IP}"
    networks:
      - services
networks:
  services:
