services:
  eureka:
    env_file:
      - ./common.env
      - ./service-discovery-svr/common.env
  proxy:
    env_file:
      - ./common.env
  execution-engine:
    env_file:
      - ./common.env
      - ./execution-engine/dev.env
    extra_hosts:
      - "postgres:${POSTGRES_IP}"
  webapi:
    env_file:
      - ./common.env
      - ./webapi/dev.env
    extra_hosts:
      - "postgres:${POSTGRES_IP}"
  gis-service:
    env_file:
      - ./common.env
      - ./gis-service/dev.env
    extra_hosts:
      - "postgres:${POSTGRES_IP}"
