server:
  port: 0
  ssl:
    enabled: true

spring:
  application:
    name: execution-engine
  profiles:
    active: default,base,dev

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/