spring:
  application:
    name: proxy-svr
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 5555

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: routes,filters

# See ZuulProperties.sensitiveHeaders for default values ("Cookie", "Set-Cookie", "Authorization")
zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon.ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000