server:
  port: 0
  context-path: /

spring:
  application:
    name: webapi
  profiles:
    active: default, webapi-postgresql
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
executionengine:
  url: http://localhost:5555/execution-engine/api/v1/